# Site settings
# in the templates available like {{ site.myvariable }}.
title: 旭日东升
email: 184659946@qq.com
brand: 孟旭东
headline: 勿问成功的秘诀为何，且尽全力做你应该做的事吧。
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msunrise.github.io" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 184659946@qq.com
phone:  

# Tracking
googleAnalitycsID: UA-83933844-1

